version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: miltera-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miltera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.2.9-alpine
    container_name: miltera-redis
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data: